[versions]
versionCode = "17"
versionName = "3.2.1"

targetSdk = "36"
compileSdk = "36"
minSdk = "29"

javaVersion = "17"
agp = "8.11.1"
workManager = "2.10.3"
argon2kt = "1.6.0"
bcrypt = "0.10.2"
faceDetection = "16.1.7"
kotlinxCoroutinesTest = "1.10.2"
rules = "1.7.0"
accompanistPermissions = "0.37.3"
coreSplashscreen = "1.0.1"
lifecycleRuntimeCompose = "2.9.2"
lifecycleViewModel = "2.9.2"
materialIconsExtended = "1.7.8"
mockk = "1.14.5"
kim = "0.26"
kotlin = "2.2.0"
kotlinx-serialization = "1.9.0"
runtimeLivedata = "1.8.3"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
navigation3 = "1.0.0-alpha06"
nav3Material = "1.0.0-SNAPSHOT"
lifecycleViewmodel = "1.0.0-alpha04"
koin-bom = "4.1.0"
cryptographyBom = "0.5.0"
datastorePreferences = "1.1.7"
timber = "5.0.1"
zoomable = "2.8.1"
cameraCamera2 = "1.4.2"
cameraView = "1.4.2"
foundation = "1.8.3"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCamera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModel" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
argon2kt = { module = "com.lambdapioneer.argon2kt:argon2kt", version.ref = "argon2kt" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
cryptography-bom = { group = "dev.whyoleg.cryptography", name = "cryptography-bom", version.ref = "cryptographyBom" }
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk" }
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kim = { module = "com.ashampoo:kim", version.ref = "kim" }
koin-android-test = { module = "io.insert-koin:koin-android-test" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodel" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-material3-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "nav3Material" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
